version: '3'

services:

  bgfaker:
    image: 'bgfaker'
    container_name: 'bgfaker'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    command: node src/main.js
    env_file: .env
    ports:
      - "8090:8090"
    expose:
      - "8090"

volumes:
  logs: { }
